services:
  web:
    restart: unless-stopped
    build: .
    environment:
      - DEBUG_MODE=${DEBUG_MODE:-false}

      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      
      - PYTHONUNBUFFERED=1
      - TEMP_DIR=/tmp
      
      - JOB_TIMEOUT=${JOB_TIMEOUT:-300}
      - GUNICORN_TIMEOUT=${GUNICORN_TIMEOUT:-300}
      
      - REMARKABLE_INPUT_PROFILE=${REMARKABLE_INPUT_PROFILE:-default}
      - REMARKABLE_OUTPUT_PROFILE=${REMARKABLE_OUTPUT_PROFILE:-generic_eink_hd}
      - REMARKABLE_BASE_FONT_SIZE=${REMARKABLE_BASE_FONT_SIZE:-12}
      - REMARKABLE_DEFAULT_FONT_SIZE=${REMARKABLE_DEFAULT_FONT_SIZE:-18}
      - REMARKABLE_MONO_FONT_SIZE=${REMARKABLE_MONO_FONT_SIZE:-16}
      - REMARKABLE_EMBED_ALL_FONTS=${REMARKABLE_EMBED_ALL_FONTS:-true}
      - REMARKABLE_SUBSET_EMBEDDED_FONTS=${REMARKABLE_SUBSET_EMBEDDED_FONTS:-true}
      - REMARKABLE_UNSMARTEN_PUNCTUATION=${REMARKABLE_UNSMARTEN_PUNCTUATION:-true}
      - REMARKABLE_CUSTOM_SIZE=${REMARKABLE_CUSTOM_SIZE:-1620x2160}
      - REMARKABLE_UNIT=${REMARKABLE_UNIT:-devicepixel}
      - REMARKABLE_PDF_SANS_FAMILY=${REMARKABLE_PDF_SANS_FAMILY:-IBM Plex Sans}
      - REMARKABLE_PDF_SERIF_FAMILY=${REMARKABLE_PDF_SERIF_FAMILY:-IBM Plex Serif}
      - REMARKABLE_PDF_MONO_FAMILY=${REMARKABLE_PDF_MONO_FAMILY:-IBM Plex Mono}
      - REMARKABLE_PDF_STANDARD_FONT=${REMARKABLE_PDF_STANDARD_FONT:-serif}
      - REMARKABLE_PDF_PAGE_MARGIN_LEFT=${REMARKABLE_PDF_PAGE_MARGIN_LEFT:-72}
      - REMARKABLE_PDF_PAGE_MARGIN_RIGHT=${REMARKABLE_PDF_PAGE_MARGIN_RIGHT:-20}
      - REMARKABLE_PDF_PAGE_MARGIN_TOP=${REMARKABLE_PDF_PAGE_MARGIN_TOP:-20}
      - REMARKABLE_PDF_PAGE_MARGIN_BOTTOM=${REMARKABLE_PDF_PAGE_MARGIN_BOTTOM:-20}
      - REMARKABLE_PRESERVE_COVER_ASPECT_RATIO=${REMARKABLE_PRESERVE_COVER_ASPECT_RATIO:-true}
      - REMARKABLE_CHANGE_JUSTIFICATION=${REMARKABLE_CHANGE_JUSTIFICATION:-justify}
      
      - BOOX_AIR_4C_INPUT_PROFILE=${BOOX_AIR_4C_INPUT_PROFILE:-default}
      - BOOX_AIR_4C_OUTPUT_PROFILE=${BOOX_AIR_4C_OUTPUT_PROFILE:-generic_eink_hd}
      - BOOX_AIR_4C_BASE_FONT_SIZE=${BOOX_AIR_4C_BASE_FONT_SIZE:-12}
      - BOOX_AIR_4C_DEFAULT_FONT_SIZE=${BOOX_AIR_4C_DEFAULT_FONT_SIZE:-16}
      - BOOX_AIR_4C_MONO_FONT_SIZE=${BOOX_AIR_4C_MONO_FONT_SIZE:-14}
      - BOOX_AIR_4C_EMBED_ALL_FONTS=${BOOX_AIR_4C_EMBED_ALL_FONTS:-true}
      - BOOX_AIR_4C_SUBSET_EMBEDDED_FONTS=${BOOX_AIR_4C_SUBSET_EMBEDDED_FONTS:-true}
      - BOOX_AIR_4C_UNSMARTEN_PUNCTUATION=${BOOX_AIR_4C_UNSMARTEN_PUNCTUATION:-true}
      - BOOX_AIR_4C_CUSTOM_SIZE=${BOOX_AIR_4C_CUSTOM_SIZE:-1860x2480}
      - BOOX_AIR_4C_UNIT=${BOOX_AIR_4C_UNIT:-devicepixel}
      - BOOX_AIR_4C_PDF_SANS_FAMILY=${BOOX_AIR_4C_PDF_SANS_FAMILY:-IBM Plex Sans}
      - BOOX_AIR_4C_PDF_SERIF_FAMILY=${BOOX_AIR_4C_PDF_SERIF_FAMILY:-IBM Plex Serif}
      - BOOX_AIR_4C_PDF_MONO_FAMILY=${BOOX_AIR_4C_PDF_MONO_FAMILY:-IBM Plex Mono}
      - BOOX_AIR_4C_PDF_STANDARD_FONT=${BOOX_AIR_4C_PDF_STANDARD_FONT:-serif}
      - BOOX_AIR_4C_PDF_PAGE_MARGIN_LEFT=${BOOX_AIR_4C_PDF_PAGE_MARGIN_LEFT:-72}
      - BOOX_AIR_4C_PDF_PAGE_MARGIN_RIGHT=${BOOX_AIR_4C_PDF_PAGE_MARGIN_RIGHT:-20}
      - BOOX_AIR_4C_PDF_PAGE_MARGIN_TOP=${BOOX_AIR_4C_PDF_PAGE_MARGIN_TOP:-20}
      - BOOX_AIR_4C_PDF_PAGE_MARGIN_BOTTOM=${BOOX_AIR_4C_PDF_PAGE_MARGIN_BOTTOM:-20}
      - BOOX_AIR_4C_PRESERVE_COVER_ASPECT_RATIO=${BOOX_AIR_4C_PRESERVE_COVER_ASPECT_RATIO:-true}
      - BOOX_AIR_4C_CHANGE_JUSTIFICATION=${BOOX_AIR_4C_CHANGE_JUSTIFICATION:-justify}
    
    network_mode: bridge
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: gunicorn app:app -b 0.0.0.0:80 -w 4 --timeout ${GUNICORN_TIMEOUT:-300}